### ISSUE TITLE
Need help with configuration

### ISSUE THREAD

**Issue by ferbulous** [afarago/esphome_component_bthome#13]
Hi, I have wall switch (bthome receiver) with 3 light bulbs (bthome transmitter)
Is there an example on how I could have the bthome receiver transmit button clicks to toggle all the lights for the nodes?
If I'm describing the roles correctly. 
Or would I need another esp as bthome receiver and the rest configured as transmitter?

Since there's an issue using esp32 as receiver, what's the maximum nodes for a receiver on esp8266?

**Comment by juleskers** [comment]
Hi @ferbulous, just in case it's still relevant two years later:

Your wall switch is likely the "transmitter", the bulbs the receiver.
The bulbs *may* also transmit things like their on/off status.
The bulbs will need to be configured somehow, to respond to the exact same input, in the same way.

You can use an ESP32, if you use [my fork](https://github.com/juleskers/esphome_component_bthome), which includes community-fixes to enable the `esp-idf` backend.

You can use an ESP as a sniffer device, to spy on the packets your wall-switch is sending, *assuming* that your wallswitch sends bthome packets (you don't actually write which device you have)

I use this config snippet to debug-log the packets sent by my Shelly BLU button RC4:

```yaml 
esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://juleskers/esphome_component_bthome

wifi:
# YOUR SETTINGS HERE

esp32_ble_tracker:
  scan_parameters:
    active: false # only passively listen, which is sufficient for bthome

bthome_ble_receiver:
  dump: unmatched
```
