### ISSUE TITLE
Matching problem when property has multiple object ids

### ISSUE THREAD

**Issue by Kimotu** [afarago/esphome_component_bthome#2]
I tried to transmit voltage. 
```

sensor:
  - platform: beethowen_receiver
    mac_address: 11:22:33:44:55:55
    sensors:
      - measurement_type: voltage
        name: Temperature
```

But the receiver does not recognize it (unmatched), because there are multiple object ids for this property. The `count` property even has three object ids. I tried to use the numeric value `measurement_type: 0x0C` but also no success.

<html><body>

Object id | Property | Data type | Factor | Example | Result | Unit
-- | -- | -- | -- | -- | -- | --
0x0C | voltage | uint16 (2 bytes) | 0.001 | 0C020C | 3.074 | V
0x4A | voltage | uint16 (2 bytes) | 0.1 | 4A020C | 307.4 | V

</body>
</html>
