### ISSUE TITLE
Feature Request: Support events (at least buttons)

### ISSUE THREAD

**Issue by Kimotu** [afarago/esphome_component_bthome#4]
I tried to transmit a button press, because I need a remote control for a stop watch. But `measurement_type: button` seems to be unsupported. I tried a workaround with `measurement_type: running` which may cause user exceptions when `delayed_off` is too high (see other [issue](https://github.com/afarago/esphome_component_bthome/issues/5))

<html><body>

Object id | Device type | Event id | Event type | Event property | Example | Result
-- | -- | -- | -- | -- | -- | --
0x3A | button | 0x00 | None |   | 3A00 |  
  |   | 0x01 | press |   | 3A01 | press
  |   | 0x02 | double_press |   | 3A02 | double_press
  |   | 0x03 | triple_press |   | 3A03 | triple_press
  |   | 0x04 | long_press |   | 3A04 | long_press
  |   | 0x05 | long_double_press |   | 3A05 | long_double_press
  |   | 0x06 | long_triple_press |   | 3A06 | long_triple_press
0x3C | dimmer | 0x00 | None |   | 3C00 |  
  |   | 0x01 | rotate left | # steps | 3C0103 | rotate left 3 steps
  |   | 0x02 | rotate right | # steps | 3C020A | rotate right 10 steps

</body>
</html>

**Comment by afarago** [comment]
This should be easy to implement from technical channel delivery perspective.
Would you mind adding your thoughts from high level flow perspective?

Major concern is that ESPNow / Beethowen has no delivery guarantee.

Please add details on the following and I might find time to implement
* how would yaml (transmitter and receiver) perspective this feature should look like - (possible interface) ?
* how would you deal with packet loss
* how would you deal with multiple events of same type - would it be even possible?
* any BTHome examples to understand the usage pattern?

Additionally:
* is 0x3C00 a valid payload? May we assume it is not? -- thus 0x3C type is 3 bytes long

**Comment by Kimotu** [comment]
Well, at least `press` and `double_press` could be implemented like this:

Transmitter:
```
beethowen_transmitter:
  id: bh_transmitter
  connect_persistent: true
  auto_send: true
  sensors:
    - measurement_type: button
      sensor_id: button

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: D6
      inverted: true
      mode:
        input: true
        pullup: true
    name: Button
    on_press:
      - beethowen_transmitter.send:
          complete_only: false
          button_event: press
#        button_event: 0x01
# if delayed_on is configured, take this value for delay before sending event
    on_click:
      - beethowen_transmitter.send:
          complete_only: false
          button_event: press
#        button_event: 0x01
#  auto send button-event 'None' after default time (e.g. 100ms) or configured delayed_off value
    on_double_click:
      - beethowen_transmitter.send:
          complete_only: false
          button_event: double_press
#        button_event: 0x02
    on_release:
       - beethowen_transmitter.send:
            complete_only: false
            button_event: None
#          button_event: 0x00
# if delayed_off is configured, take this value for delay before sending event
```

Receiver:

```
beethowen_receiver:

  local_passkey: ${local_pass}
  devices:
    - mac_address: "11:22:33:44:55:66"
      name_prefix: Beethowen Receiver

binary_sensor:
  - platform: beethowen_receiver
    mac_address: "11:22:33:44:55:66"
    sensors:
      - measurement_type: button
        name: button
        on_press:
          - logger.log: "Pressed"
        on_click:
          - logger.log: "Pressed/Clicked"
        on_double_click:
          - logger.log: "Double-pressed"
        on_release:
          - logger.log: "Released"
```

I must admit, I am not so happy with the naming. BTHome calls it press and double-pressed, but in ESPHome it is more like a click and double-click.

But you should have a look at [Wifi NOW](https://deploy-preview-775--esphome.netlify.app/components/wifi_now.html#wifi-now-inject) how there this issue is handled.

**Comment by afarago** [comment]
Thanks for the hints:

Transmitter side I have put in came up with a first implementation:

```yaml
beethowen_transmitter:
  id: bh_transmitter
  connect_persistent: true
  auto_send: true

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    name: Button
    id: user_button
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - beethowen_transmitter.send_event: button_click
      - min_length: 351ms
        max_length: 3000ms
        then:
          - beethowen_transmitter.send_event: button_long_click
    on_double_click:
      - beethowen_transmitter.send_event: button_double_click
```

I am not sure to even consider the value of auto_send here, or handle a queue / re-send upon failure.
The first implementation sends all events right away and (if not restarted) holds a queue of max 5 event items.

The button-event 'None'  does not seem to be necessary for me.

---

On receiver side there are several questions about design yet.
I do not see a viable option to re-use the binary_sensor events as it has internal evaluation based on timings of the state change, therefore the only place I see to add these are the code is the device section.

```yaml
beethowen_receiver:
  local_passkey: 0x5678
  on_event: # on_event(address, event) - all catching event trigger
    - lambda: |-
        ESP_LOGI("app", "event received {device_type} 0x%x {event_type} %d ({steps} %d)",
          event.device_type, event.event_type, event.steps);
   on_button_click: # event handler for any device (address, event(device_type=measurement_type, event_type=subevent, steps-for dimmer)
    # ...
  devices:
    - mac_address: AA:BB:CC:DD:EE:FF
      name_prefix: Beethowen ABCDEF TestDevice
      dump: unmatched
      expected_remote_passkey: 0x2345
      on_event: # on_event(address, event) - events for this specific device
        - lambda: |-
            ESP_LOGI("app", "event received {device_type} %d {event_type} %d {steps} %d",
              x.device_type, x.event_type, x.steps);
      on_packet: # on_packet(address, measurements) - packets for this specific device
        # ...
      on_button_click: # event handler for this device (address, event(device_type=measurement_type, event_type=subevent, steps-for dimmer)
        # ...
      on_button_double_click:
        # ...
      on_dimmer_left:
        # ...
      on_dimmer_right: # (address, event(device_type=measurement_type, event_type=subevent, steps-for dimmer)
        # ...

```

I still need to put some effort into finalizing the design.
Let me know what do you think, or if you have any better ideas.

**Comment by afarago** [comment]
Added first iteration of eventing (see the examples).

Keeping this ticket open for further enhancements:
* named events (e.g. on_button_click)
* device node specific events

**Comment by afarago** [comment]
Closing with event and per device event handling added and documented.

**Comment by ferbulous** [comment]
hi, sorry to bump this issue
I'm trying to add button press but I'm getting this error

![image](https://github.com/afarago/esphome_component_bthome/assets/24526737/97114e98-2557-4031-b865-d618f0b1edd0)

Do I need to change the measurement type?

**Comment by afarago** [comment]
Check out the "on_event" trigger .
https://github.com/afarago/esphome_component_bthome/blob/master/components/docs/beethowen_receiver.rst#on_event

Background: events are not really fit for sensors imo as they would only pose state for a spike.

Hope it helps ;)

**Comment by ferbulous** [comment]
My apologize, I still don't quite understand this
Are you suggesting this is not suitable for button presses events from transmitter?
I tried using your code example from (https://github.com/afarago/esphome_component_bthome/issues/4#issuecomment-1663715444) but now I'm getting a different error
```
beethowen_transmitter:
  id: bh_transmitter
  connect_persistent: true
  auto_send: true

binary_sensor:
  - platform: status
    name: $devicename Status
  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_click:
      - beethowen_transmitter.send_event: button_click
```
![image](https://github.com/afarago/esphome_component_bthome/assets/24526737/bf5d6d2a-4c0d-4a4a-a5e6-0af47d142999)
