### ISSUE TITLE
ESP32 crashes on beethowen_server example

### ISSUE THREAD

**Issue by jov58** [afarago/esphome_component_bthome#7]
Hi,

I was looking for esp-now examples and came across your code. I tried your beethowen-server/remote example on two Wemos Lolin ESP32-S3 devices. For now, I'm just trying to send the state of a GPIO pin to another ESP. So I adapted the code for my specific device and stripped out the BMP085 (don't have one) and deep sleep parts (don't need it).

Both example files compile without errors, but the beethowen-server example crashes. It looks like something in beethowen_receiver_hub.cpp, but perhaps I am doing something wrong? The receiver example seems to work fine (except it can't find the server yet of course).

Do you have any idea what could cause this crash?

Log from server ESP:
```
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x420957fe
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x39c
load:0x403c9700,len:0x9bc
load:0x403cc700,len:0x28dc
entry 0x403c98c0
[I][logger:262]: Log initialized
[I][app:029]: Running through setup()...
[C][beethowen_receiver:029]: Setting up BeethowenReceiverHub...
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x420552bf  PS      : 0x00060e30  A0      : 0x820074a5  A1      : 0x3fce2cd0  
A2      : 0x3fc9bd64  A3      : 0x3fcef940  A4      : 0x3fc9bd64  A5      : 0x00000000  
A6      : 0x00060a20  A7      : 0x00000001  A8      : 0x820118a0  A9      : 0x3fce2c60  
A10     : 0x3fce3170  A11     : 0x00000004  A12     : 0x3c0a1e51  A13     : 0x0000001d  
A14     : 0x3c0a1e2e  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0000004c  LBEG    : 0x400556d5  LEND    : 0x400556e5  LCOUNT  : 0xffffffed  
```

Complete yaml for the server:
```
substitutions:
  systemName: "beethowen-srv"

esphome:
  name: $systemName
  platformio_options:
    board_build.flash_mode: dio
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
    board_upload.flash_size: 16MB
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "/config/esphome/devices/wemos-lolin-s3-partitions.csv"

external_components:
  - source: github://afarago/esphome_component_bthome
    refresh: 1min

esp32:
  board: lolin_s3

api:

web_server:
  port: 80
  ota: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: ## this is needed as ESP-NOW demands AP
    ssid: "$systemName"
    password: !secret wifi_password

logger:
  level: debug

time:
  - platform: homeassistant
    id: my_time
    timezone: Europe/Amsterdam

beethowen_receiver:
  # dump: all
  # local_passkey: 0x1234
  #       //id(lastupdate_ts).publish_state(time_ts);
  devices:
    - mac_address: !secret mac_lolin_s3_B
      name_prefix: Beethowen Receiver
      dump: all

binary_sensor:
  - platform: beethowen_receiver
    mac_address: !secret mac_lolin_s3_B
    sensors:
      - measurement_type: generic_boolean
        name: button_blue

sensor:
  - platform: beethowen_receiver
    mac_address: !secret mac_lolin_s3_B
    sensors:
      - measurement_type: count_4
        name: Count
        unit_of_measurement: cycles
      - measurement_type: duration
        name: Cycle time

text_sensor:
  - platform: template
    id: lastupdate
    name: ${systemName}.Last Update

```

**Comment by lorenzspenger** [comment]
Same issue here. Did you get it working?

**Comment by dgdavid** [comment]
Similar issue here when trying to set a node as receiver by using an example

```
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:326]: Log initialized
[I][app:029]: Running through setup()...
[C][beethowen_receiver:029]: Setting up BeethowenReceiverHub...
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x401313a4  PS      : 0x00060030  A0      : 0x800d7969  A1      : 0x3ffb2500  
A2      : 0x3ffc6068  A3      : 0x3ffc067c  A4      : 0x3ffc6068  A5      : 0x00000000  
A6      : 0x00060c20  A7      : 0x00000001  A8      : 0x800e0dd4  A9      : 0x3ffb2490  
A10     : 0x3ffb8a58  A11     : 0x00000004  A12     : 0x3f400db9  A13     : 0x0000001d  
A14     : 0x3f400d96  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0000004c  LBEG    : 0x40089965  LEND    : 0x40089975  LCOUNT  : 0xffffffed  


Backtrace:0x401313a1:0x3ffb25000x400d7966:0x3ffb2520 0x400d79e7:0x3ffb2540 0x4016df51:0x3ffb2580 0x4016dfc9:0x3ffb25a0 0x400e033c:0x3ffb25c0 0x400e1ec6:0x3ffb25f0 0x400ecd7e:0x3ffb2820
```


The config relevant part 


```yml
# Example configuration entry
external_components:
  - source: github://afarago/esphome_component_bthome

beethowen_receiver:

# Individual sensors
sensor:
  - platform: beethowen_receiver
    mac_address: 3C:E9:0E:AD:BC:04
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: 0x02
        name: Temperature_Second
        accuracy_decimals: 2
        unit_of_measurement: °C
```

**Comment by afarago** [comment]
I am sorry, I also experience problems on ESP32 boards, yet was not able to get to the root cause.
Hopefully during the winter period I get to it or someone starts debugging and pinpoints the problem.

**Comment by dgdavid** [comment]
> Similar issue here when trying to set a node as receiver by using an example

However, I was able to run the bthome_* components, just in case it can help.

```yaml
switch:
  - platform: gpio
    id: sample_relay
    name: "Just an example"
    pin: 26
    inverted: true
    on_turn_on:
    - delay: 2s
    - switch.turn_off: sample_relay
 
external_components:
  - source: github://afarago/esphome_component_bthome
    components: [ bthome_base, bthome_receiver_base, bthome_ble_receiver ]

esp32_ble_tracker:

bthome_ble_receiver:
  devices:
    mac_address: 11:22:33:44:55:66
    on_button_click:
      - switch.turn_on: sample_relay
      
```

The above example just works, although it always logs 

> [D][bthome_receiver_base:147]: Invalid Object ID found in payload - 120

For completeness, the _ble transmitter_ is a ShellyBLU Button1.

**Comment by dgdavid** [comment]
I realized that it works too without selecting components, 

```yaml
switch:
  - platform: gpio
    id: sample_relay
    name: "Just an example"
    pin: 26
    inverted: true
    on_turn_on:
    - delay: 2s
    - switch.turn_off: sample_relay
 
external_components:
  - source: github://afarago/esphome_component_bthome
    #components: [ bthome_base, bthome_receiver_base, bthome_ble_receiver ]

esp32_ble_tracker:

bthome_ble_receiver:
  devices:
    mac_address: 11:22:33:44:55:66
    on_button_click:
      - switch.turn_on: sample_relay
 ```

So, looks like the problem is in be beethowen_* components.

Please, excuse me for the noise in this thread... I'm a complete newbie in that field. Just trying to add information that can help to narrow where the problem is.
